apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kope-routing
  labels:
    tier: routing
    app: kope-routing
    version: v1
spec:
  template:
    metadata:
      labels:
        name: kope-routing
    spec:
      # Filter to specific nodes:
      # nodeSelector:
      #  app: kope-routing
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
          image: kope/route-controller
          name: kope-routing
          command: [ "/usr/bin/route-controller", "--provider=ipsec", "--system-uuid", "/sys/class/dmi/id/product_uuid" ]
          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
